### ISSUE TITLE
trouble with install

### ISSUE THREAD

**Issue by AlexProfi** [Keyintegrity/pycryptoprosdk#15]
Hello I try to use on with cryptopro 5
and get error
    In file included from pycryptoprosdk/libpycades.cpp:8:
    pycryptoprosdk/libpycades.cpp: In function ‘char* GetHashOidByKeyOid(char*)’:
    /opt/cprocsp/include/cpcsp/WinCryptEx.h:1164:29: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     1164 | #define szOID_CP_GOST_R3411 "1.2.643.2.2.9"
          |                             ^~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp:35:13: note: in expansion of macro ‘szOID_CP_GOST_R3411’
       35 |      return szOID_CP_GOST_R3411;
          |             ^~~~~~~~~~~~~~~~~~~
    /opt/cprocsp/include/cpcsp/WinCryptEx.h:1165:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     1165 | #define szOID_CP_GOST_R3411_12_256 "1.2.643.7.1.1.2.2"
          |                                    ^~~~~~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp:38:13: note: in expansion of macro ‘szOID_CP_GOST_R3411_12_256’
       38 |      return szOID_CP_GOST_R3411_12_256;
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/cprocsp/include/cpcsp/WinCryptEx.h:1166:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     1166 | #define szOID_CP_GOST_R3411_12_512 "1.2.643.7.1.1.2.3"
          |                                    ^~~~~~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp:41:13: note: in expansion of macro ‘szOID_CP_GOST_R3411_12_512’
       41 |      return szOID_CP_GOST_R3411_12_512;
          |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp: At global scope:
    pycryptoprosdk/libpycades.cpp:655:27: error: variable ‘PyModuleDef libpycades’ has initializer but incomplete type
      655 | static struct PyModuleDef libpycades = {
          |                           ^~~~~~~~~~
    pycryptoprosdk/libpycades.cpp:656:5: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
      656 |     PyModuleDef_HEAD_INIT,
          |     ^~~~~~~~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp: In function ‘void PyInit_libpycades()’:
    pycryptoprosdk/libpycades.cpp:666:9: error: ‘PyModule_Create’ was not declared in this scope; did you mean ‘PyModule_Check’?
      666 |     m = PyModule_Create(&libpycades);
          |         ^~~~~~~~~~~~~~~
          |         PyModule_Check
    pycryptoprosdk/libpycades.cpp:668:43: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
      668 |     CertDoesNotExist = PyErr_NewException("libpycades.CertDoesNotExist", NULL, NULL);
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    pycryptoprosdk/libpycades.cpp:672:12: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
      672 |     return m;
          |            ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
how to fix this?

**Comment by uishnik** [comment]
Похоже ты пытаешься установить pycryptoprosdk в python2. pycryptoprosdk изначально разрабатывался под python >= 3.5 и не совместим с версией 2. Напишу об этом в README.rst.

**Comment by AlexProfi** [comment]
Да точно. нет ли возможности модифицировать чтобы запускать под питон 2?

**Comment by AlexProfi** [comment]
проверил на другой среде под 3 встало без проблем

**Comment by uishnik** [comment]
python 2 давно прекратил официальную поддержку, поэтому нет смысла под него адаптировать.
