### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by J4CKVVH173** [Keyintegrity/pycryptoprosdk#5]
В README.md есть кусок примера кода `with open('certificate.cer'), 'rb') as f:`.  Тут лишняя закрывающая скобка.
И в `Dockerfile` используется `/opt/cprocsp/bin/amd64/certmgr -inst -store uca -f /certs/kazna.cer`, хотя данны сертификат отсутвует в `certs/`. Где его можно получить?

**Comment by uishnik** [comment]
Лишнюю скобку удалил, спасибо! Сертификат можно скачать на официальном сайте росказначейства. Но для работы пакета он не нужен. В докерфайле он просто для примера.
