### ISSUE TITLE
Получение публичного сертификата

### ISSUE THREAD

**Issue by J4CKVVH173** [Keyintegrity/pycryptoprosdk#7]
Есть ли возможность получить сам файл публичного сертификата, не в виде объекта, а в виде file-like object или конкретно в виде файла. Из примеров вижу, что сертификат можно положить в хранилище, или удалить, а просто получить публичную часть возможности нет

**Comment by lexapi** [comment]
что значит file-like object ? Получите объект https://github.com/Keyintegrity/pycryptoprosdk/blob/master/pycryptoprosdk/__init__.py#L94 и записывайте в нужном вам формате в файл, если это необходимо или куда угодно.
Экземпляр класса CertInfo это мапинг этой структуры https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/ns-wincrypt-cert_info

Нужно что-то другое ?

**Comment by J4CKVVH173** [comment]
File-like object в питоне, объект имеющий интерфейся, как если бы это был объект чтения из файла. Модуль io позволяет получать такие объекты. 
Да, это то что нужно, спасибо
