### ISSUE TITLE
Can't create cert content

### ISSUE THREAD

**Issue by ogremagi4** [Keyintegrity/pycryptoprosdk#9]
Спасибо за труд.

`libpycades.install_certificate('MY', cert_content)`
возвращает
`Exception: Can't create cert context.`

`cert_content`
`
b'-----BEGIN CERTIFICATE-----\nMIICrjCCAhcCAgPoMA0GCSqGSIb3DQEBBQUAMIGeMQswCQYDVQQGEwJSVTEPMA0G\nA1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxFzAVBgNVBAoMDk5la3Jhc292\na2EgbGliMRcwFQYDVQQLDA5OZWtyYXNvdmthIGxpYjE7MDkGA1UEAwwy0J/QvtC3\n0LTQvdGP0LrQvtCyINCk0LjQu9C40L/QvyDQodC10YDQs9C10LXQstC40YcwHhcN\nMjEwMTMxMDEwNjA0WhcNMzEwMTI5MDEwNjA0WjCBnjELMAkGA1UEBhMCUlUxDzAN\nBgNVBAgMBk1vc2NvdzEPMA0GA1UEBwwGTW9zY293MRcwFQYDVQQKDA5OZWtyYXNv\ndmthIGxpYjEXMBUGA1UECwwOTmVrcmFzb3ZrYSBsaWIxOzA5BgNVBAMMMtCf0L7Q\nt9C00L3Rj9C60L7QsiDQpNC40LvQuNC/0L8g0KHQtdGA0LPQtdC10LLQuNGHMIGf\nMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD0XfCZ8M6S/yKFg06NQpANxtYxOuzH\n9L3L47XB2A16DEUJaFfWPLaQK+hNNb1UjxWzMib754b4FVvvZFVulmhohNySwem4\nTifUsKjm0KQ9iAnHEI62QQ3Lwn1fpL6CpYOUKuKfgMsqdq2rTa1dHNRLOgohvez1\nY7o2hZC7PqZL8QIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAOwJAlyYdU1eYOdysWKj\nm73lxo/bEme8YPpa0AdqHT87YQdQoYXkVAmTk8VYrc0p1HGigVTnFrZKAGfzuvPN\nTTIH9wsf+xiifLGjal83j9bE6vSKvBqzzEHa6wXtgqI4DKHqicQAw2xEuVxGLnZ5\nejwuOSQsLZRF93YBbtVCRKhX\n-----END CERTIFICATE-----\n'`

Подскажите, в какую сторону копать?

**Comment by uishnik** [comment]
А зачем вы обращаетесь напрямую к `libpycades`? Устанавливать сертификат нужно так:
```
from pycryptoprosdk import CryptoProSDK
sdk = CryptoProSDK()
sdk.install_certificate('MY', cert_content)
```
Кроме того, вам необходимо убрать из контента сертификата строки `-----BEGIN CERTIFICATE-----\n` и `-----END CERTIFICATE-----\n`, т.к. метод install_certificate может обрабатывать только строки, закодированные в base64.

т.е. такой код:
```
from pycryptoprosdk import CryptoProSDK
sdk = CryptoProSDK()
cert_content = b'MIICrjCCAhcCAgPoMA0GCSqGSIb3DQEBBQUAMIGeMQswCQYDVQQGEwJSVTEPMA0G\nA1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxFzAVBgNVBAoMDk5la3Jhc292\na2EgbGliMRcwFQYDVQQLDA5OZWtyYXNvdmthIGxpYjE7MDkGA1UEAwwy0J/QvtC3\n0LTQvdGP0LrQvtCyINCk0LjQu9C40L/QvyDQodC10YDQs9C10LXQstC40YcwHhcN\nMjEwMTMxMDEwNjA0WhcNMzEwMTI5MDEwNjA0WjCBnjELMAkGA1UEBhMCUlUxDzAN\nBgNVBAgMBk1vc2NvdzEPMA0GA1UEBwwGTW9zY293MRcwFQYDVQQKDA5OZWtyYXNv\ndmthIGxpYjEXMBUGA1UECwwOTmVrcmFzb3ZrYSBsaWIxOzA5BgNVBAMMMtCf0L7Q\nt9C00L3Rj9C60L7QsiDQpNC40LvQuNC/0L8g0KHQtdGA0LPQtdC10LLQuNGHMIGf\nMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD0XfCZ8M6S/yKFg06NQpANxtYxOuzH\n9L3L47XB2A16DEUJaFfWPLaQK+hNNb1UjxWzMib754b4FVvvZFVulmhohNySwem4\nTifUsKjm0KQ9iAnHEI62QQ3Lwn1fpL6CpYOUKuKfgMsqdq2rTa1dHNRLOgohvez1\nY7o2hZC7PqZL8QIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAOwJAlyYdU1eYOdysWKj\nm73lxo/bEme8YPpa0AdqHT87YQdQoYXkVAmTk8VYrc0p1HGigVTnFrZKAGfzuvPN\nTTIH9wsf+xiifLGjal83j9bE6vSKvBqzzEHa6wXtgqI4DKHqicQAw2xEuVxGLnZ5\nejwuOSQsLZRF93YBbtVCRKhX\n'
sdk.install_certificate('MY', cert_content)
```
работает корректно.

**Comment by ogremagi4** [comment]
Это помогло, спасибо.
